Update nav.component.html
Fixed issue:
ERROR in src/app/layout/nav/nav.component.html(17,29): Property 'isDarkTheme' does not exist on type 'NavComponent'. Did you mean 'isDarkTheme$'?